services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - .:/code
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://jennacooper@host.docker.internal:5432/warbler
    command: flask run --host=0.0.0.0 --port=9001
